### ISSUE TITLE
Why does the readme install this as a dev dependency?

### ISSUE THREAD

**Issue by douglasg14b** [ectoflow/vue-stripe-js#30]
This means it won't be built into production bundles.

**Comment by softbeehive** [comment]
Hi Douglas, dev dependency in readme is due to my muscle memory. Bundlers like Rollup, Webpack, and Parcel don't differentiate between `dependencies` and `devDependencies`. As long as you import the package in the source code somewhere in the tree of your entry file, it ends up in the production bundle. I tested it with Vite.

When you run `npm install --production`, npm installs only the dependencies. In that case, move it to dependencies.

I'll consider updating the readme
